title = "Irace Kenny Experiments"

[test]
exec = "ls"
args = "-l"

[irace]
exec = "./parallel-irace-mpi"
args = "20 foraging_50kNEWdep --parallel 15 --scenario scenario_foraging_50k.txt"

[irace.foraging]
args = "10 foraging_50kNEWdep --parallel 15 --scenario scenario_foraging_50k.txt"

[irace.foraging2]
args = "11 foraging_50kNEWdep --parallel 15 --scenario scenario_foraging.txt"

[neat]
args = "12 foraging_50kNEWdep --parallel 15 --scenario scenario_foraging_50k.txt"

[neat.foraging]
exec = "./parallel-irace-mpi2"

[neat.foraging2]
args = "13 foraging_50kNEWdep --parallel 15 --scenario scenario_foraging.txt"

